### ISSUE TITLE
With io.cucumber:cucumber-java:3.x  throws error

### ISSUE THREAD

**Issue by garikKalash** [reportportal/agent-java-cucumber2#3]
Is added agent-java-cucumber2 with  io.cucumber:cucumber-java:3.0.2 , and as a result have this error

_**java.lang.IncompatibleClassChangeError: Found interface cucumber.api.TestCase, but class was expected...**_

problem solves when I decrease the version of cucumber into 2.x,

tested for 3.0.1, 3.0.0 versions to the same error throws.

**Comment by scormaq** [comment]
@garikKalash that's right, cucumber-jvm 3.x has breaking changes. From its announcement (https://cucumber.io/blog/2018/05/19/announcing-cucumber-jvm-3-0-0):
_To support the invoke around semantics the **TestStep event has been replaced with an interface**. Its concrete implementation split into HookTestStep and PickleStepTestStep. All subclass specific methods in TestStep have been deprecated._

So it is not an agent issue. I think there should be another **agent-java-cucumber3** agent to support cucumber-jvm 3+ 😃

**Comment by DzmitryHumianiuk** [comment]
@garikKalash @scormaq folks, could you plz push first lines of cone for **agent-java-cucumber3**?

**Comment by revaultch** [comment]
Haven't done a full regression, but for now it seems to be a matter of recompilation:
https://github.com/revaultch/agent-java-cucumber3

https://jitpack.io/#revaultch/agent-java-cucumber3

```
        <dependency>
            <groupId>com.github.revaultch</groupId>
            <artifactId>agent-java-cucumber3</artifactId>
            <version>add1e21fc3</version>
        </dependency>
```

**Comment by DzmitryHumianiuk** [comment]
@revaultch awesome!
forked

**Comment by revaultch** [comment]
I moved the changes to branches:
- https://github.com/revaultch/agent-java-cucumber/tree/cucumber3
- https://github.com/revaultch/agent-java-cucumber/tree/cucumber4

https://jitpack.io/#revaultch/agent-java-cucumber
