### ISSUE TITLE
Cucumber version issues 2, 3, 4

### ISSUE THREAD

**Issue by revaultch** [reportportal/agent-java-cucumber2#4]
Relates to #3 
It seems that cucumber changed there API from 2->3 and 3->4.
2->3 only required a recompile
3->4 requires some changes in the code

Would you be able to provide the three different artifact versions by introducing branches cucumber3 and cucumber4 in this repository? 

See branches:
https://github.com/revaultch/agent-java-cucumber/tree/cucumber3
https://github.com/revaultch/agent-java-cucumber/tree/cucumber4

**Comment by urs-ikentoo-com** [comment]
Yes you can just create a repo for each version, I guess. However there really is not much change in the code. So configuring build and deploy to different artifacts on a per branch basis might be better to merge changes applying to all branches.

I'm not sure how you handle builds and deploys to central depending on how it is done it might be easier to create multiple repositories.

@DzmitryHumianiuk 
You can try version4 under https://github.com/revaultch/agent-java-cucumber/tree/cucumber4 through jitpack, it is working in parallell builds, but has a  problem regrouping report subitems when running on different threads.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu what do you think?
this should be your decision.
